# Generated by Django 5.1.1 on 2024-12-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga_name', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('male_population', models.IntegerField()),
                ('female_population', models.IntegerField()),
                ('year', models.IntegerField(default=2023)),
                ('growth_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('density', models.IntegerField()),
                ('households', models.IntegerField()),
            ],
        ),
    ]
